language: node_js
node_js:
  - 13
branchs:
  only:
    - master
cache:
  directories:
    - node_modules
install:
  - npm install
scripts:
  - npm run build
after_success:
  - scp /.nuxt root@182.92.214.223:/home/lib/nuxt-product
  - pm2 delete nuxt-product
  - pm2 start npm --name nuxt-product -- run start
