language: node_js
node_js:
  - 13
branchs:
  only:
    - master
cache:
  directories:
    - node_modules
install:
  - npm install
scripts:
  - npm run build
before_install:
  - openssl aes-256-cbc -K $encrypted_fa8c133d16af_key -iv $encrypted_fa8c133d16af_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host 182.92.214.223\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
  - cd /nuxt-project
  - npm run build
  - ls -a
  - scp /.nuxt root@182.92.214.223:/home/lib/nuxt-product
  - ssh root@182.92.214.223 'pm2 delete nuxt && pm2 start npm --name nuxt -- run start'
